firstname="Sathish"
middlename="Kumar"
lastname="Yellanki"
houseno="2-435-76/A"
streetname="S R Nagar"
cityname="Hyderabad"
state="Telangana"
country="India"
pincode=500038
emailid="yellankibigdata0301@gmail.com"
phone="+91-8142190906"
echo "The First Name is : $firstname"
echo "The Middle Name is : $middlename"
echo "The Last Name is : $lastname"
echo "The Full Name is : $firstname $middlename $lastname"
echo "The Address of $firstname $middlename $lastname is..."
echo "Address"
echo "-------"
echo "House Number : $houseno"
echo "Land Mark OR Street And City : $streetname, $cityname"
echo "State And Country Details : $statename, $country"
echo "Pin OR Zip Code : $pincode"
echo "Mailing Contact : $emailID, Contact Phone Number : $phone"
